const cars = [
    {
        name: "mits2020",
        make: "Mitsubishi",
        model: "Outlander",
        year:  "2020",
        color: "Silver",
        seats: "7",
        doors: "4",
        locationCity: "Seattle",
        locationState: "WA",
        vin: "JA4AD3A32LZO42682",
        license: "RYT-2162",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "",
        insuranceDate: "12-31-2022",
        fuelType: "Gas",
        photos: ["mits2020.jpeg","mits2020-1.jpeg"]
    },
    {
        name: "camrybl2023",
        make: "Toyota",
        model: "Camry",
        year:  "2023",
        color: "Blue",
        seats: "5",
        doors: "4",
        location: "Temple, TX",
        vin: "4T1C11AK7PU095400",
        license: "shp-7827",
        locationCity: "Temple",
        locationState: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        fuelType: "Gas",
        photos: ["camrybl2023.jpeg","camrybl2023-1.jpeg"]
    },
    {
        name: "jeepGC2022",
        make: "Jeep",
        model: "Grand Cherokee",
        year:  "2022",
        color: "Black",
        seats: "5",
        doors: "4",
        locationCity: "Temple",
        locationState: "TX",
        vin: "",
        license: "",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        fuelType: "Hybrid",
        photos: ["jeepGC2022.jpg","jeepGC2022-1.jpg"]
    },
  ]
  
  //at the bottom of /models/fruits.js
  module.exports = cars