const cars = [
    {
        name: "mits2020",
        make: "Mitsubishi",
        model: "Outlander",
        year:  "2020",
        color: "Silver",
        mileage: 2500,
        seats: "7",
        doors: "4",
        type: "Midsize SUV",
        locationCity: "Seattle",
        locationState: "WA",
        vin: "JA4AD3A32LZO42682",
        license: "RYT-2162",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "",
        insuranceDate: "12-31-2022",
        fuelType: "Gas",
        photos: ["mits2020.jpeg","mits2020-1.jpeg"]
    },
    {
        name: "camrybl2023",
        make: "Toyota",
        model: "Camry",
        year:  "2023",
        color: "Blue",
        mileage: 2500,
        seats: "5",
        doors: "4",
        type: "Midsize Sedan",
        location: "Temple, TX",
        vin: "4T1C11AK7PU095400",
        license: "SHP-7827",
        locationCity: "Temple",
        locationState: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        fuelType: "Gas",
        photos: ["camrybl2023.jpeg","camrybl2023-1.jpeg"]
    },
    {
        name: "jeepGC2022",
        make: "Jeep",
        model: "Grand Cherokee",
        year:  "2022",
        color: "Black",
        mileage: 2500,
        seats: "5",
        doors: "4",
        type: "Fullsize SUV",
        locationCity: "Temple",
        locationState: "TX",
        vin: "1C4RJYC68N8706872",
        license: "SLP-1988",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        fuelType: "Hybrid",
        photos: ["jeepGC2022.jpg","jeepGC2022-1.jpg"]
    },
    {
        name: "equinoxGray2022",
        make: "Chevrolet",
        model: "Equinox",
        year:  "2022",
        color: "Gray",
        mileage: 5000,
        seats: "5",
        doors: "4",
        type: "Midsize SUV",
        locationCity: "Temple",
        locationState: "TX",
        vin: "3GNAXKEV2NS239475",
        license: "SHP-2943",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        fuelType: "Gas",
        photos: ["equinoxGray2022.jpg","equinoxGray2022-1.jpg"]
    },
  ]
  
  //at the bottom of /models/fruits.js
  module.exports = cars