const cars = [
    {
        name: "mits2020",
        make: "Mitsubishi",
        model: "Outlander",
        year:  "2020",
        color: "Silver",
        mileage: 2500,
        seats: "7",
        doors: "4",
        type: "Midsize SUV",
        drive: "FWD",
        fuelType: "Gas",
        price: "75",
        locationCity: "Seattle",
        locationState: "WA",
        vin: "JA4AD3A32LZO42682",
        license: "RYT-2162",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "",
        insuranceDate: "12-31-2022",
        photos: ["mits2020.jpeg","mits2020-1.jpeg"]
    },
    {
        name: "camrybl2023",
        make: "Toyota",
        model: "Camry",
        year:  "2023",
        color: "Blue",
        mileage: 2500,
        seats: "5",
        doors: "4",
        type: "Midsize Sedan",
        drive: "FWD",
        fuelType: "Gas",
        price: "65",
        location: "Temple, TX",
        vin: "4T1C11AK7PU095400",
        license: "SHP-7827",
        locationCity: "Temple",
        locationState: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        photos: ["camrybl2023.jpeg","camrybl2023-1.jpeg"]
    },
    {
        name: "jeepGC2022",
        make: "Jeep",
        model: "Grand Cherokee",
        year:  "2022",
        color: "Black",
        mileage: 7100,
        seats: "5",
        doors: "4",
        type: "Fullsize SUV",
        drive: "4x4",
        fuelType: "Hybrid",
        price: "100",
        locationCity: "Temple",
        locationState: "TX",
        vin: "1C4RJYC68N8706872",
        license: "SLP-1988",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        photos: ["jeepGC2022.jpg","jeepGC2022-1.jpg"]
    },
    {
        name: "equinoxGray2022",
        make: "Chevrolet",
        model: "Equinox",
        year:  "2022",
        color: "Gray",
        mileage: 5000,
        seats: "5",
        doors: "4",
        type: "Midsize SUV",
        drive: "FWD",
        fuelType: "Gas",
        price: "65",
        locationCity: "Temple",
        locationState: "TX",
        vin: "3GNAXKEV2NS239475",
        license: "SHP-2943",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        photos: ["equinoxGray2022.jpg","equinoxGray2022-1.jpg"]
    },
    {
        name: "chevyMalibu2021",    
        make: "Chevrolet",
        model: "Malibu",
        year:  "2021",
        color: "Black",
        mileage: 5000,
        seats: "5",
        doors: "4",
        type: "Midsize Sedan",
        drive: "FWD",
        fuelType: "Gas",
        price: "65",
        locationCity: "Temple",
        locationState: "TX",
        vin: "1G1ZG5ST1MF078712",
        license: "RYT-2348",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        photos: ["chevyMalibu2021.jpg","chevyMalibu2021-1.jpg","chevyMalibu2021-2.jpg","chevyMalibu2021-3.jpg"]
    },
    {
        name: "equinoxSlv2022",
        make: "Chevrolet",
        model: "Equinox",
        year:  "2022",
        color: "Gray",
        mileage: 5000,
        seats: "5",
        doors: "4",
        type: "Midsize SUV",
        drive: "FWD",
        fuelType: "Gas",
        price: "65",
        locationCity: "Temple",
        locationState: "TX",
        vin: "3GNAXKEV3NS191830",
        license: "RYS-3891",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        photos: ["equinoxSlv2022.jpg","equinoxSlv2022-1.jpg","equinoxSlv2022-2.jpg","equinoxSlv2022-3.jpg"]
    },
    {
        name: "subaruCross2021",
        make: "Subaru",
        model: "CrossTrek",
        year:  "2021",
        color: "White",
        mileage: 5000,
        seats: "5",
        doors: "4",
        type: "Midsize SUV",
        drive: "AWD",
        fuelType: "Gas",
        price: "65",
        locationCity: "Temple",
        locationState: "TX",
        vin: "JF2GTHRCOMH248954",
        license: "SHP-3638",
        registration: "TX",
        registrationDate: "08-01-2022",
        insurance: "Geico",
        insuranceDate: "01-23-2023",
        photos: ["subaruCross2021.jpg","subaruCross2021-1.jpg","subaruCross2021-2.jpg","subaruCross2021-3.jpg"]
    },
  ]
  
  module.exports = cars